/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as SuperAgent from "../../../../../api";
import * as core from "../../../../../core";

export const AgentDatasource: core.serialization.Schema<serializers.AgentDatasource.Raw, SuperAgent.AgentDatasource> =
    core.serialization.object({
        datasourceId: core.serialization.string(),
    });

export declare namespace AgentDatasource {
    interface Raw {
        datasourceId: string;
    }
}
