/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as SuperAgent from "../../../../../api";
import * as core from "../../../../../core";

export const AppModelsRequestAgent: core.serialization.Schema<
    serializers.AppModelsRequestAgent.Raw,
    SuperAgent.AppModelsRequestAgent
> = core.serialization.object({
    isActive: core.serialization.boolean().optional(),
    name: core.serialization.string(),
    type: core.serialization.string().optional(),
    initialMessage: core.serialization.string().optional(),
    prompt: core.serialization.string().optional(),
    llmModel: core.serialization.string().optional(),
    llmProvider: core.serialization.lazy(async () => (await import("../../../..")).LlmProvider).optional(),
    description: core.serialization.string().optional(),
    avatar: core.serialization.string().optional(),
    openaiOptions: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace AppModelsRequestAgent {
    interface Raw {
        isActive?: boolean | null;
        name: string;
        type?: string | null;
        initialMessage?: string | null;
        prompt?: string | null;
        llmModel?: string | null;
        llmProvider?: serializers.LlmProvider.Raw | null;
        description?: string | null;
        avatar?: string | null;
        openaiOptions?: Record<string, unknown> | null;
    }
}
