/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as SuperAgent from "../../../../../api";
import * as core from "../../../../../core";

export const AgentDocument: core.serialization.Schema<serializers.AgentDocument.Raw, SuperAgent.AgentDocument> =
    core.serialization.object({
        agentId: core.serialization.string(),
        documentId: core.serialization.string(),
    });

export declare namespace AgentDocument {
    interface Raw {
        agentId: string;
        documentId: string;
    }
}
