/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as SuperAgent from "../../../../../api";
import * as core from "../../../../../core";

export const AppLibModelsAgentDocumentAgentDocument: core.serialization.Schema<
    serializers.AppLibModelsAgentDocumentAgentDocument.Raw,
    SuperAgent.AppLibModelsAgentDocumentAgentDocument
> = core.serialization.object({
    agentId: core.serialization.string(),
    documentId: core.serialization.string(),
});

export declare namespace AppLibModelsAgentDocumentAgentDocument {
    interface Raw {
        agentId: string;
        documentId: string;
    }
}
