/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ListRunsApiV1RunsGetRequest {
    agentId?: string;
    fromPage?: number;
    toPage?: number;
    limit?: number;
    workflowId?: string;
}
