/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ToolUpdate {
    name?: string;
    description?: string;
    type?: string;
    metadata?: Record<string, unknown>;
    returnDirect?: boolean;
}
