/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as SuperAgent from "../../../../../api";
import * as core from "../../../../../core";

export const AppModelsRequestApiUser: core.serialization.Schema<
    serializers.AppModelsRequestApiUser.Raw,
    SuperAgent.AppModelsRequestApiUser
> = core.serialization.object({
    email: core.serialization.string(),
});

export declare namespace AppModelsRequestApiUser {
    interface Raw {
        email: string;
    }
}
