/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as SuperAgent from "../../../../../api";
import * as core from "../../../../../core";

export const AppModelsRequestWorkflowStep: core.serialization.Schema<
    serializers.AppModelsRequestWorkflowStep.Raw,
    SuperAgent.AppModelsRequestWorkflowStep
> = core.serialization.object({
    order: core.serialization.number(),
    agentId: core.serialization.string(),
    input: core.serialization.string(),
    output: core.serialization.string(),
});

export declare namespace AppModelsRequestWorkflowStep {
    interface Raw {
        order: number;
        agentId: string;
        input: string;
        output: string;
    }
}
