/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as SuperAgent from "../../../../../api";
import * as core from "../../../../../core";

export const WorkflowInvoke: core.serialization.Schema<serializers.WorkflowInvoke.Raw, SuperAgent.WorkflowInvoke> =
    core.serialization.object({
        input: core.serialization.string(),
        enableStreaming: core.serialization.boolean(),
    });

export declare namespace WorkflowInvoke {
    interface Raw {
        input: string;
        enableStreaming: boolean;
    }
}
