/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as SuperAgent from "../../../../../api";
import * as core from "../../../../../core";

export const WorkflowStep: core.serialization.Schema<serializers.WorkflowStep.Raw, SuperAgent.WorkflowStep> =
    core.serialization.object({
        order: core.serialization.number(),
        agentId: core.serialization.string(),
        input: core.serialization.string(),
        output: core.serialization.string(),
    });

export declare namespace WorkflowStep {
    interface Raw {
        order: number;
        agentId: string;
        input: string;
        output: string;
    }
}
