/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type AgentType = "SUPERAGENT" | "OPENAI_ASSISTANT" | "LLM";

export const AgentType = {
    Superagent: "SUPERAGENT",
    OpenaiAssistant: "OPENAI_ASSISTANT",
    Llm: "LLM",
} as const;
