/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SuperAgent from "..";

export interface AgentList {
    success: boolean;
    data?: SuperAgent.PrismaModelsAgent[];
}
