/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SuperAgent from "..";

/**
 * Represents a ApiKey record
 */
export interface ApiKeyCreateModel {
    id: string;
    name: string;
    displayApiKey: string;
    createdAt: Date;
    updatedAt: Date;
    apiUserId: string;
    apiUser?: SuperAgent.PrismaModelsApiUser;
    apiKey: string;
}
