/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AppLibModelsResponseTag {
    id: string;
    name: string;
    color?: string;
    userId: string;
    createdAt?: Date;
    updatedAt?: Date;
}
