/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SuperAgent from "..";

export interface AppLibModelsResponseAgent {
    id: string;
    description?: string;
    avatarUrl?: string;
    shareableToken?: string;
    userId: string;
    documentId?: string;
    toolId?: string;
    tags?: Record<string, unknown>[];
    promptId?: string;
    prompt?: Record<string, unknown>;
    name: string;
    type: SuperAgent.AgentType;
    llm: Record<string, unknown>;
    hasMemory: boolean;
    isPublic: boolean;
    isListed: boolean;
    createdAt?: Date;
    updatedAt?: Date;
}
