/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AppLibModelsResponseApiToken {
    id: string;
    userId: string;
    description: string;
    token: string;
}
