/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SuperAgent from "..";

export interface AppLibModelsResponseDocument {
    id: string;
    description?: string;
    userId: string;
    type: SuperAgent.DocumentType;
    url?: string;
    content?: string;
    contentHash?: string;
    name: string;
    splitter?: Record<string, unknown>;
    createdAt?: Date;
    updatedAt?: Date;
    index?: Record<string, unknown>;
    authorization?: Record<string, unknown>;
    metadata?: Record<string, unknown>;
}
