/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SuperAgent from "..";

export interface AppLibModelsResponseAgentTool {
    id: string;
    toolId?: string;
    tool?: SuperAgent.AppLibModelsResponseTool;
    agentId: string;
    createdAt?: Date;
    updatedAt?: Date;
    deletedAt?: Date;
}
