/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SuperAgent from "..";

export interface AppLibModelsResponseTool {
    id: string;
    name: string;
    description?: string;
    type?: SuperAgent.ToolType;
    metadata?: Record<string, unknown>;
    userId: string;
    returnDirect: boolean;
    createdAt?: Date;
    updatedAt?: Date;
}
