/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SuperAgent from "..";

export interface AppModelsResponseWorkflow {
    success: boolean;
    data?: SuperAgent.PrismaModelsWorkflow;
}
