/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AppModelsResponseAgentInvokeStream {
    /** The type of the event. */
    event?: string;
    /** The data associated with the event. */
    data?: string;
}
