/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AppModelsRequestApiUser {
    email: string;
    firstName?: string;
    lastName?: string;
    company?: string;
    anonymousId?: string;
}
