/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AppModelsRequestDatasource {
    name: string;
    description: string;
    type: string;
    content?: string;
    url?: string;
    metadata?: Record<string, unknown>;
}
