/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SuperAgent from "..";

export interface AppModelsRequestDatasource {
    name: string;
    description?: string;
    type: string;
    content?: string;
    url?: string;
    metadata?: Record<string, unknown>;
    vectorDbId?: string;
    embeddingsModelProvider?: SuperAgent.EmbeddingsModelProvider;
}
