/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SuperAgent from "..";

export interface AppModelsRequestVectorDb {
    provider: SuperAgent.VectorDbProvider;
    options: Record<string, unknown>;
}
