/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SuperAgent from "..";

export interface AppModelsResponseVectorDb {
    success: boolean;
    data?: SuperAgent.PrismaModelsVectorDb;
}
