/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AppModelsRequestAgent {
    isActive?: boolean;
    name: string;
    initialMessage?: string;
    prompt?: string;
    llmModel: string;
    description: string;
    avatar?: string;
}
