/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type DatasourceStatus = "IN_PROGRESS" | "DONE";

export const DatasourceStatus = {
    InProgress: "IN_PROGRESS",
    Done: "DONE",
} as const;
