/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type DatasourceType =
    | "TXT"
    | "PDF"
    | "CSV"
    | "PPTX"
    | "XLSX"
    | "DOCX"
    | "GOOGLE_DOC"
    | "YOUTUBE"
    | "GITHUB_REPOSITORY"
    | "MARKDOWN"
    | "WEBPAGE"
    | "AIRTABLE"
    | "STRIPE"
    | "NOTION"
    | "SITEMAP"
    | "URL"
    | "FUNCTION";

export const DatasourceType = {
    Txt: "TXT",
    Pdf: "PDF",
    Csv: "CSV",
    Pptx: "PPTX",
    Xlsx: "XLSX",
    Docx: "DOCX",
    GoogleDoc: "GOOGLE_DOC",
    Youtube: "YOUTUBE",
    GithubRepository: "GITHUB_REPOSITORY",
    Markdown: "MARKDOWN",
    Webpage: "WEBPAGE",
    Airtable: "AIRTABLE",
    Stripe: "STRIPE",
    Notion: "NOTION",
    Sitemap: "SITEMAP",
    Url: "URL",
    Function: "FUNCTION",
} as const;
