/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type DocumentType =
    | "TXT"
    | "PDF"
    | "CSV"
    | "YOUTUBE"
    | "OPENAPI"
    | "URL"
    | "MARKDOWN"
    | "FIRESTORE"
    | "PSYCHIC"
    | "GITHUB_REPOSITORY"
    | "WEBPAGE"
    | "STRIPE"
    | "AIRTABLE"
    | "SITEMAP"
    | "NOTION";

export const DocumentType = {
    Txt: "TXT",
    Pdf: "PDF",
    Csv: "CSV",
    Youtube: "YOUTUBE",
    Openapi: "OPENAPI",
    Url: "URL",
    Markdown: "MARKDOWN",
    Firestore: "FIRESTORE",
    Psychic: "PSYCHIC",
    GithubRepository: "GITHUB_REPOSITORY",
    Webpage: "WEBPAGE",
    Stripe: "STRIPE",
    Airtable: "AIRTABLE",
    Sitemap: "SITEMAP",
    Notion: "NOTION",
} as const;
