/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type EmbeddingsModelProvider = "OPENAI" | "AZURE_OPENAI";

export const EmbeddingsModelProvider = {
    Openai: "OPENAI",
    AzureOpenai: "AZURE_OPENAI",
} as const;
