/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FunctionDefinition {
    name?: string;
    description?: string;
    parameters?: Record<string, unknown>;
}
