/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type LlmModel = "GPT_3_5_TURBO_16K_0613" | "GPT_3_5_TURBO_0613" | "GPT_4_0613" | "GPT_4_32K_0613";

export const LlmModel = {
    Gpt35Turbo16K0613: "GPT_3_5_TURBO_16K_0613",
    Gpt35Turbo0613: "GPT_3_5_TURBO_0613",
    Gpt40613: "GPT_4_0613",
    Gpt432K0613: "GPT_4_32K_0613",
} as const;
