/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type LlmProvider = "OPENAI" | "AZURE_OPENAI" | "HUGGINGFACE";

export const LlmProvider = {
    Openai: "OPENAI",
    AzureOpenai: "AZURE_OPENAI",
    Huggingface: "HUGGINGFACE",
} as const;
