/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SuperAgent from "..";

export interface OpenAiAssistantParameters {
    metadata?: Record<string, unknown>;
    fileIds?: string[];
    tools?: SuperAgent.OpenAiAssistantParametersToolsItem[];
}
