/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SuperAgent from "..";

export type OpenAiAssistantParametersToolsItem =
    | SuperAgent.OpenAiAssistantParametersToolsItem.CodeInterpreter
    | SuperAgent.OpenAiAssistantParametersToolsItem.Retrieval
    | SuperAgent.OpenAiAssistantParametersToolsItem.Function;

export declare namespace OpenAiAssistantParametersToolsItem {
    interface CodeInterpreter extends SuperAgent.ToolAssistantToolsCode {
        type: "code_interpreter";
    }

    interface Retrieval extends SuperAgent.ToolAssistantToolsRetrieval {
        type: "retrieval";
    }

    interface Function extends SuperAgent.ToolAssistantToolsFunction {
        type: "function";
    }
}
