/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SuperAgent from "..";

/**
 * Represents a AgentDatasource record
 */
export interface PrismaModelsAgentDatasource {
    agentId: string;
    datasourceId: string;
    agent?: SuperAgent.PrismaModelsAgent;
    datasource?: SuperAgent.PrismaModelsDatasource;
    createdAt: Date;
    updatedAt: Date;
}
