/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SuperAgent from "..";

/**
 * Represents a AgentLLM record
 */
export interface PrismaModelsAgentLlm {
    agentId: string;
    llmId: string;
    agent?: SuperAgent.PrismaModelsAgent;
    llm?: SuperAgent.PrismaModelsLlm;
    createdAt: Date;
    updatedAt: Date;
}
