/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SuperAgent from "..";

/**
 * Represents a WorkflowStep record
 */
export interface PrismaModelsWorkflowStep {
    id: string;
    order: number;
    workflowId: string;
    workflow?: SuperAgent.PrismaModelsWorkflow;
    createdAt: Date;
    updatedAt: Date;
    input: string;
    output: string;
    agentId: string;
    agent?: SuperAgent.PrismaModelsAgent;
}
