/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SuperAgent from "..";

/**
 * Represents a AgentTool record
 */
export interface PrismaModelsAgentTool {
    agentId: string;
    toolId: string;
    agent?: SuperAgent.PrismaModelsAgent;
    tool?: SuperAgent.PrismaModelsTool;
    createdAt: Date;
    updatedAt: Date;
}
