/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SuperAgent from "..";

/**
 * Represents a LLM record
 */
export interface PrismaModelsLlm {
    id: string;
    provider: SuperAgent.LlmProvider;
    apiKey: string;
    options?: string;
    agents?: SuperAgent.PrismaModelsAgentLlm[];
    createdAt: Date;
    updatedAt: Date;
    apiUserId: string;
    apiUser?: SuperAgent.PrismaModelsApiUser;
}
