/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SuperAgent from "..";

export interface TagListOutput {
    success: boolean;
    data: SuperAgent.AppLibModelsResponseTag[];
}
