/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SuperAgent from "..";

export interface TagOutput {
    success: boolean;
    data?: SuperAgent.AppLibModelsResponseTag;
}
