/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type ToolType =
    | "BROWSER"
    | "SEARCH"
    | "WOLFRAM_ALPHA"
    | "REPLICATE"
    | "ZAPIER_NLA"
    | "AGENT"
    | "OPENAPI"
    | "CHATGPT_PLUGIN"
    | "METAPHOR";

export const ToolType = {
    Browser: "BROWSER",
    Search: "SEARCH",
    WolframAlpha: "WOLFRAM_ALPHA",
    Replicate: "REPLICATE",
    ZapierNla: "ZAPIER_NLA",
    Agent: "AGENT",
    Openapi: "OPENAPI",
    ChatgptPlugin: "CHATGPT_PLUGIN",
    Metaphor: "METAPHOR",
} as const;
