/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SuperAgent from "..";

export interface ToolListOutput {
    success: boolean;
    data: SuperAgent.AppLibModelsResponseTool[];
}
