/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type ToolType =
    | "ALGOLIA"
    | "BROWSER"
    | "BING_SEARCH"
    | "REPLICATE"
    | "WOLFRAM_ALPHA"
    | "ZAPIER_NLA"
    | "AGENT"
    | "OPENAPI"
    | "CHATGPT_PLUGIN"
    | "METAPHOR"
    | "PUBMED"
    | "CODE_EXECUTOR"
    | "OPENBB"
    | "GPT_VISION"
    | "TTS_1"
    | "HAND_OFF"
    | "FUNCTION";

export const ToolType = {
    Algolia: "ALGOLIA",
    Browser: "BROWSER",
    BingSearch: "BING_SEARCH",
    Replicate: "REPLICATE",
    WolframAlpha: "WOLFRAM_ALPHA",
    ZapierNla: "ZAPIER_NLA",
    Agent: "AGENT",
    Openapi: "OPENAPI",
    ChatgptPlugin: "CHATGPT_PLUGIN",
    Metaphor: "METAPHOR",
    Pubmed: "PUBMED",
    CodeExecutor: "CODE_EXECUTOR",
    Openbb: "OPENBB",
    GptVision: "GPT_VISION",
    Tts1: "TTS_1",
    HandOff: "HAND_OFF",
    Function: "FUNCTION",
} as const;
