/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface User {
    id: string;
    email: string;
    password?: string;
    name?: string;
    createdAt?: Date;
    updatedAt?: Date;
    deletedAt?: Date;
    provider?: string;
    accessToken?: string;
}
