/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type VectorDbProvider = "PINECONE" | "ASTRA_DB" | "WEAVIATE" | "QDRANT";

export const VectorDbProvider = {
    Pinecone: "PINECONE",
    AstraDb: "ASTRA_DB",
    Weaviate: "WEAVIATE",
    Qdrant: "QDRANT",
} as const;
