/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SuperAgent from "..";

/**
 * Represents a WorkflowConfig record
 */
export interface WorkflowConfig {
    id: string;
    config?: unknown;
    createdAt: Date;
    updatedAt: Date;
    workflowId: string;
    workflow?: SuperAgent.PrismaModelsWorkflow;
    apiUser?: SuperAgent.PrismaModelsApiUser;
    apiUserId?: string;
}
