/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         email: "string"
 *     }
 */
export interface AppModelsRequestApiUser {
    email: string;
}
