/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as SuperAgent from "../../../../../api";
import * as core from "../../../../../core";

export const ApiToken: core.serialization.Schema<serializers.ApiToken.Raw, SuperAgent.ApiToken> =
    core.serialization.object({
        description: core.serialization.string(),
    });

export declare namespace ApiToken {
    interface Raw {
        description: string;
    }
}
