/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as SuperAgent from "../../../../../api";
import * as core from "../../../../../core";

export const AppLibModelsApiTokenApiToken: core.serialization.Schema<
    serializers.AppLibModelsApiTokenApiToken.Raw,
    SuperAgent.AppLibModelsApiTokenApiToken
> = core.serialization.object({
    description: core.serialization.string(),
});

export declare namespace AppLibModelsApiTokenApiToken {
    interface Raw {
        description: string;
    }
}
