/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as SuperAgent from "../../../../../api";
import * as core from "../../../../../core";

export const OAuth: core.serialization.Schema<serializers.OAuth.Raw, SuperAgent.OAuth> = core.serialization.object({
    email: core.serialization.string(),
    name: core.serialization.string(),
    accessToken: core.serialization.property("access_token", core.serialization.string().optional()),
    provider: core.serialization.string().optional(),
});

export declare namespace OAuth {
    interface Raw {
        email: string;
        name: string;
        access_token?: string | null;
        provider?: string | null;
    }
}
