/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as SuperAgent from "../../../../../api";
import * as core from "../../../../../core";

export const SignUp: core.serialization.Schema<serializers.SignUp.Raw, SuperAgent.SignUp> = core.serialization.object({
    email: core.serialization.string(),
    password: core.serialization.string(),
    name: core.serialization.string().optional(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace SignUp {
    interface Raw {
        email: string;
        password: string;
        name?: string | null;
        metadata?: Record<string, unknown> | null;
    }
}
