/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as SuperAgent from "../../../../../api";
import * as core from "../../../../../core";

export const SignIn: core.serialization.Schema<serializers.SignIn.Raw, SuperAgent.SignIn> = core.serialization.object({
    email: core.serialization.string(),
    password: core.serialization.string(),
});

export declare namespace SignIn {
    interface Raw {
        email: string;
        password: string;
    }
}
