/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const AgentToolListOutput: core.serialization.ObjectSchema<
    serializers.AgentToolListOutput.Raw,
    SuperAgent.AgentToolListOutput
> = core.serialization.object({
    success: core.serialization.boolean(),
    data: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("..")).AppLibModelsResponseAgentTool)
    ),
});

export declare namespace AgentToolListOutput {
    interface Raw {
        success: boolean;
        data: serializers.AppLibModelsResponseAgentTool.Raw[];
    }
}
