/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const AgentOutput: core.serialization.ObjectSchema<serializers.AgentOutput.Raw, SuperAgent.AgentOutput> =
    core.serialization.object({
        success: core.serialization.boolean(),
        data: core.serialization.lazyObject(async () => (await import("..")).AppLibModelsResponseAgent).optional(),
    });

export declare namespace AgentOutput {
    interface Raw {
        success: boolean;
        data?: serializers.AppLibModelsResponseAgent.Raw | null;
    }
}
