/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const AgentList: core.serialization.ObjectSchema<serializers.AgentList.Raw, SuperAgent.AgentList> =
    core.serialization.object({
        success: core.serialization.boolean(),
        data: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("..")).PrismaModelsAgent))
            .optional(),
    });

export declare namespace AgentList {
    interface Raw {
        success: boolean;
        data?: serializers.PrismaModelsAgent.Raw[] | null;
    }
}
