/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const AgentDocumentOutput: core.serialization.ObjectSchema<
    serializers.AgentDocumentOutput.Raw,
    SuperAgent.AgentDocumentOutput
> = core.serialization.object({
    success: core.serialization.boolean(),
    data: core.serialization.lazyObject(async () => (await import("..")).AppLibModelsResponseAgentDocument).optional(),
});

export declare namespace AgentDocumentOutput {
    interface Raw {
        success: boolean;
        data?: serializers.AppLibModelsResponseAgentDocument.Raw | null;
    }
}
