/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const AgentDocumentListOuput: core.serialization.ObjectSchema<
    serializers.AgentDocumentListOuput.Raw,
    SuperAgent.AgentDocumentListOuput
> = core.serialization.object({
    success: core.serialization.boolean(),
    data: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("..")).AppLibModelsResponseAgentDocument)
    ),
});

export declare namespace AgentDocumentListOuput {
    interface Raw {
        success: boolean;
        data: serializers.AppLibModelsResponseAgentDocument.Raw[];
    }
}
