/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const AgentToolOutput: core.serialization.ObjectSchema<
    serializers.AgentToolOutput.Raw,
    SuperAgent.AgentToolOutput
> = core.serialization.object({
    success: core.serialization.boolean(),
    data: core.serialization.lazyObject(async () => (await import("..")).AppLibModelsResponseAgentTool).optional(),
});

export declare namespace AgentToolOutput {
    interface Raw {
        success: boolean;
        data?: serializers.AppLibModelsResponseAgentTool.Raw | null;
    }
}
