/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const AgentListOutput: core.serialization.ObjectSchema<
    serializers.AgentListOutput.Raw,
    SuperAgent.AgentListOutput
> = core.serialization.object({
    success: core.serialization.boolean(),
    data: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("..")).AppLibModelsResponseAgent)
    ),
});

export declare namespace AgentListOutput {
    interface Raw {
        success: boolean;
        data: serializers.AppLibModelsResponseAgent.Raw[];
    }
}
