/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const ApiKeyCreate: core.serialization.ObjectSchema<serializers.ApiKeyCreate.Raw, SuperAgent.ApiKeyCreate> =
    core.serialization.object({
        success: core.serialization.boolean(),
        data: core.serialization.lazyObject(async () => (await import("..")).ApiKeyCreateModel).optional(),
    });

export declare namespace ApiKeyCreate {
    interface Raw {
        success: boolean;
        data?: serializers.ApiKeyCreateModel.Raw | null;
    }
}
