/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const ApiKeyList: core.serialization.ObjectSchema<serializers.ApiKeyList.Raw, SuperAgent.ApiKeyList> =
    core.serialization.object({
        success: core.serialization.boolean(),
        data: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("..")).PrismaModelsApiKey))
            .optional(),
    });

export declare namespace ApiKeyList {
    interface Raw {
        success: boolean;
        data?: serializers.PrismaModelsApiKey.Raw[] | null;
    }
}
