/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const ApiTokenOutput: core.serialization.ObjectSchema<
    serializers.ApiTokenOutput.Raw,
    SuperAgent.ApiTokenOutput
> = core.serialization.object({
    success: core.serialization.boolean(),
    data: core.serialization.lazyObject(async () => (await import("..")).AppLibModelsResponseApiToken).optional(),
});

export declare namespace ApiTokenOutput {
    interface Raw {
        success: boolean;
        data?: serializers.AppLibModelsResponseApiToken.Raw | null;
    }
}
