/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const ApiTokenListOutput: core.serialization.ObjectSchema<
    serializers.ApiTokenListOutput.Raw,
    SuperAgent.ApiTokenListOutput
> = core.serialization.object({
    success: core.serialization.boolean(),
    data: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("..")).AppLibModelsResponseApiToken)
    ),
});

export declare namespace ApiTokenListOutput {
    interface Raw {
        success: boolean;
        data: serializers.AppLibModelsResponseApiToken.Raw[];
    }
}
