/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const AppLibModelsResponseTag: core.serialization.ObjectSchema<
    serializers.AppLibModelsResponseTag.Raw,
    SuperAgent.AppLibModelsResponseTag
> = core.serialization.object({
    id: core.serialization.string(),
    name: core.serialization.string(),
    color: core.serialization.string().optional(),
    userId: core.serialization.string(),
    createdAt: core.serialization.date().optional(),
    updatedAt: core.serialization.date().optional(),
});

export declare namespace AppLibModelsResponseTag {
    interface Raw {
        id: string;
        name: string;
        color?: string | null;
        userId: string;
        createdAt?: string | null;
        updatedAt?: string | null;
    }
}
