/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const AppLibModelsResponseDocument: core.serialization.ObjectSchema<
    serializers.AppLibModelsResponseDocument.Raw,
    SuperAgent.AppLibModelsResponseDocument
> = core.serialization.object({
    id: core.serialization.string(),
    description: core.serialization.string().optional(),
    userId: core.serialization.string(),
    type: core.serialization.lazy(async () => (await import("..")).DocumentType),
    url: core.serialization.string().optional(),
    content: core.serialization.string().optional(),
    contentHash: core.serialization.string().optional(),
    name: core.serialization.string(),
    splitter: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    createdAt: core.serialization.date().optional(),
    updatedAt: core.serialization.date().optional(),
    index: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    authorization: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace AppLibModelsResponseDocument {
    interface Raw {
        id: string;
        description?: string | null;
        userId: string;
        type: serializers.DocumentType.Raw;
        url?: string | null;
        content?: string | null;
        contentHash?: string | null;
        name: string;
        splitter?: Record<string, unknown> | null;
        createdAt?: string | null;
        updatedAt?: string | null;
        index?: Record<string, unknown> | null;
        authorization?: Record<string, unknown> | null;
        metadata?: Record<string, unknown> | null;
    }
}
