/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const AppLibModelsResponseAgentTool: core.serialization.ObjectSchema<
    serializers.AppLibModelsResponseAgentTool.Raw,
    SuperAgent.AppLibModelsResponseAgentTool
> = core.serialization.object({
    id: core.serialization.string(),
    toolId: core.serialization.string().optional(),
    tool: core.serialization.lazyObject(async () => (await import("..")).AppLibModelsResponseTool).optional(),
    agentId: core.serialization.string(),
    createdAt: core.serialization.date().optional(),
    updatedAt: core.serialization.date().optional(),
    deletedAt: core.serialization.date().optional(),
});

export declare namespace AppLibModelsResponseAgentTool {
    interface Raw {
        id: string;
        toolId?: string | null;
        tool?: serializers.AppLibModelsResponseTool.Raw | null;
        agentId: string;
        createdAt?: string | null;
        updatedAt?: string | null;
        deletedAt?: string | null;
    }
}
