/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const AppLibModelsResponsePrompt: core.serialization.ObjectSchema<
    serializers.AppLibModelsResponsePrompt.Raw,
    SuperAgent.AppLibModelsResponsePrompt
> = core.serialization.object({
    id: core.serialization.string(),
    name: core.serialization.string(),
    template: core.serialization.string(),
    inputVariables: core.serialization.property(
        "input_variables",
        core.serialization.list(core.serialization.unknown())
    ),
    userId: core.serialization.string(),
    createdAt: core.serialization.date().optional(),
    updatedAt: core.serialization.date().optional(),
    deletedAt: core.serialization.date().optional(),
});

export declare namespace AppLibModelsResponsePrompt {
    interface Raw {
        id: string;
        name: string;
        template: string;
        input_variables: unknown[];
        userId: string;
        createdAt?: string | null;
        updatedAt?: string | null;
        deletedAt?: string | null;
    }
}
