/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const AppLibModelsResponseAgentDocument: core.serialization.ObjectSchema<
    serializers.AppLibModelsResponseAgentDocument.Raw,
    SuperAgent.AppLibModelsResponseAgentDocument
> = core.serialization.object({
    id: core.serialization.string(),
    documentId: core.serialization.string().optional(),
    document: core.serialization.lazyObject(async () => (await import("..")).AppLibModelsResponseDocument).optional(),
    agentId: core.serialization.string(),
    createdAt: core.serialization.date().optional(),
    updatedAt: core.serialization.date().optional(),
    deletedAt: core.serialization.date().optional(),
});

export declare namespace AppLibModelsResponseAgentDocument {
    interface Raw {
        id: string;
        documentId?: string | null;
        document?: serializers.AppLibModelsResponseDocument.Raw | null;
        agentId: string;
        createdAt?: string | null;
        updatedAt?: string | null;
        deletedAt?: string | null;
    }
}
