/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const AppModelsResponseAgentInvokeStream: core.serialization.ObjectSchema<
    serializers.AppModelsResponseAgentInvokeStream.Raw,
    SuperAgent.AppModelsResponseAgentInvokeStream
> = core.serialization.object({
    event: core.serialization.string().optional(),
    data: core.serialization.string().optional(),
});

export declare namespace AppModelsResponseAgentInvokeStream {
    interface Raw {
        event?: string | null;
        data?: string | null;
    }
}
