/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const AppModelsResponseAgent: core.serialization.ObjectSchema<
    serializers.AppModelsResponseAgent.Raw,
    SuperAgent.AppModelsResponseAgent
> = core.serialization.object({
    success: core.serialization.boolean(),
    data: core.serialization.lazyObject(async () => (await import("..")).PrismaModelsAgent).optional(),
});

export declare namespace AppModelsResponseAgent {
    interface Raw {
        success: boolean;
        data?: serializers.PrismaModelsAgent.Raw | null;
    }
}
