/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const AppModelsResponseApiUser: core.serialization.ObjectSchema<
    serializers.AppModelsResponseApiUser.Raw,
    SuperAgent.AppModelsResponseApiUser
> = core.serialization.object({
    success: core.serialization.boolean(),
    data: core.serialization.lazyObject(async () => (await import("..")).PrismaModelsApiUser).optional(),
});

export declare namespace AppModelsResponseApiUser {
    interface Raw {
        success: boolean;
        data?: serializers.PrismaModelsApiUser.Raw | null;
    }
}
