/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const AppModelsResponseDatasource: core.serialization.ObjectSchema<
    serializers.AppModelsResponseDatasource.Raw,
    SuperAgent.AppModelsResponseDatasource
> = core.serialization.object({
    success: core.serialization.boolean(),
    data: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace AppModelsResponseDatasource {
    interface Raw {
        success: boolean;
        data?: Record<string, unknown> | null;
    }
}
