/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const AppModelsRequestTool: core.serialization.ObjectSchema<
    serializers.AppModelsRequestTool.Raw,
    SuperAgent.AppModelsRequestTool
> = core.serialization.object({
    name: core.serialization.string(),
    description: core.serialization.string(),
    type: core.serialization.string(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    returnDirect: core.serialization.boolean().optional(),
});

export declare namespace AppModelsRequestTool {
    interface Raw {
        name: string;
        description: string;
        type: string;
        metadata?: Record<string, unknown> | null;
        returnDirect?: boolean | null;
    }
}
