/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const AppModelsResponseAgentInvoke: core.serialization.ObjectSchema<
    serializers.AppModelsResponseAgentInvoke.Raw,
    SuperAgent.AppModelsResponseAgentInvoke
> = core.serialization.object({
    success: core.serialization.boolean(),
    data: core.serialization.unknown().optional(),
});

export declare namespace AppModelsResponseAgentInvoke {
    interface Raw {
        success: boolean;
        data?: unknown | null;
    }
}
