/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const AppModelsResponseApiKey: core.serialization.ObjectSchema<
    serializers.AppModelsResponseApiKey.Raw,
    SuperAgent.AppModelsResponseApiKey
> = core.serialization.object({
    success: core.serialization.boolean(),
    data: core.serialization.lazyObject(async () => (await import("..")).PrismaModelsApiKey).optional(),
});

export declare namespace AppModelsResponseApiKey {
    interface Raw {
        success: boolean;
        data?: serializers.PrismaModelsApiKey.Raw | null;
    }
}
