/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const AppModelsResponseLlm: core.serialization.ObjectSchema<
    serializers.AppModelsResponseLlm.Raw,
    SuperAgent.AppModelsResponseLlm
> = core.serialization.object({
    success: core.serialization.boolean(),
    data: core.serialization.lazyObject(async () => (await import("..")).PrismaModelsLlm).optional(),
});

export declare namespace AppModelsResponseLlm {
    interface Raw {
        success: boolean;
        data?: serializers.PrismaModelsLlm.Raw | null;
    }
}
