/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const AppModelsResponseWorkflow: core.serialization.ObjectSchema<
    serializers.AppModelsResponseWorkflow.Raw,
    SuperAgent.AppModelsResponseWorkflow
> = core.serialization.object({
    success: core.serialization.boolean(),
    data: core.serialization.lazyObject(async () => (await import("..")).PrismaModelsWorkflow).optional(),
});

export declare namespace AppModelsResponseWorkflow {
    interface Raw {
        success: boolean;
        data?: serializers.PrismaModelsWorkflow.Raw | null;
    }
}
