/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const AppModelsRequestApiKey: core.serialization.ObjectSchema<
    serializers.AppModelsRequestApiKey.Raw,
    SuperAgent.AppModelsRequestApiKey
> = core.serialization.object({
    name: core.serialization.string(),
});

export declare namespace AppModelsRequestApiKey {
    interface Raw {
        name: string;
    }
}
