/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const AppModelsRequestVectorDb: core.serialization.ObjectSchema<
    serializers.AppModelsRequestVectorDb.Raw,
    SuperAgent.AppModelsRequestVectorDb
> = core.serialization.object({
    provider: core.serialization.string(),
    options: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace AppModelsRequestVectorDb {
    interface Raw {
        provider: string;
        options: Record<string, unknown>;
    }
}
