/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const AppModelsRequestWorkflow: core.serialization.ObjectSchema<
    serializers.AppModelsRequestWorkflow.Raw,
    SuperAgent.AppModelsRequestWorkflow
> = core.serialization.object({
    name: core.serialization.string(),
    description: core.serialization.string(),
});

export declare namespace AppModelsRequestWorkflow {
    interface Raw {
        name: string;
        description: string;
    }
}
