/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const DatasourceType: core.serialization.Schema<serializers.DatasourceType.Raw, SuperAgent.DatasourceType> =
    core.serialization.enum_([
        "TXT",
        "PDF",
        "CSV",
        "PPTX",
        "XLSX",
        "DOCX",
        "GOOGLE_DOC",
        "YOUTUBE",
        "GITHUB_REPOSITORY",
        "MARKDOWN",
        "WEBPAGE",
        "AIRTABLE",
        "STRIPE",
        "NOTION",
        "SITEMAP",
        "URL",
        "FUNCTION",
    ]);

export declare namespace DatasourceType {
    type Raw =
        | "TXT"
        | "PDF"
        | "CSV"
        | "PPTX"
        | "XLSX"
        | "DOCX"
        | "GOOGLE_DOC"
        | "YOUTUBE"
        | "GITHUB_REPOSITORY"
        | "MARKDOWN"
        | "WEBPAGE"
        | "AIRTABLE"
        | "STRIPE"
        | "NOTION"
        | "SITEMAP"
        | "URL"
        | "FUNCTION";
}
