/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const DatasourceStatus: core.serialization.Schema<
    serializers.DatasourceStatus.Raw,
    SuperAgent.DatasourceStatus
> = core.serialization.enum_(["IN_PROGRESS", "DONE", "FAILED"]);

export declare namespace DatasourceStatus {
    type Raw = "IN_PROGRESS" | "DONE" | "FAILED";
}
