/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const DocumentOuput: core.serialization.ObjectSchema<serializers.DocumentOuput.Raw, SuperAgent.DocumentOuput> =
    core.serialization.object({
        success: core.serialization.boolean(),
        data: core.serialization.lazyObject(async () => (await import("..")).AppLibModelsResponseDocument).optional(),
    });

export declare namespace DocumentOuput {
    interface Raw {
        success: boolean;
        data?: serializers.AppLibModelsResponseDocument.Raw | null;
    }
}
