/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const DocumentListOutput: core.serialization.ObjectSchema<
    serializers.DocumentListOutput.Raw,
    SuperAgent.DocumentListOutput
> = core.serialization.object({
    success: core.serialization.boolean(),
    data: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("..")).AppLibModelsResponseDocument)
    ),
});

export declare namespace DocumentListOutput {
    interface Raw {
        success: boolean;
        data: serializers.AppLibModelsResponseDocument.Raw[];
    }
}
