/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const FunctionDefinition: core.serialization.ObjectSchema<
    serializers.FunctionDefinition.Raw,
    SuperAgent.FunctionDefinition
> = core.serialization.object({
    name: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    parameters: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace FunctionDefinition {
    interface Raw {
        name?: string | null;
        description?: string | null;
        parameters?: Record<string, unknown> | null;
    }
}
