/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const LlmList: core.serialization.ObjectSchema<serializers.LlmList.Raw, SuperAgent.LlmList> =
    core.serialization.object({
        success: core.serialization.boolean(),
        data: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("..")).PrismaModelsLlm))
            .optional(),
    });

export declare namespace LlmList {
    interface Raw {
        success: boolean;
        data?: serializers.PrismaModelsLlm.Raw[] | null;
    }
}
