/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const LlmProvider: core.serialization.Schema<serializers.LlmProvider.Raw, SuperAgent.LlmProvider> =
    core.serialization.enum_(["OPENAI", "AZURE_OPENAI", "HUGGINGFACE"]);

export declare namespace LlmProvider {
    type Raw = "OPENAI" | "AZURE_OPENAI" | "HUGGINGFACE";
}
