/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const LlmParams: core.serialization.ObjectSchema<serializers.LlmParams.Raw, SuperAgent.LlmParams> =
    core.serialization.object({
        maxTokens: core.serialization.property("max_tokens", core.serialization.number()),
        temperature: core.serialization.number(),
    });

export declare namespace LlmParams {
    interface Raw {
        max_tokens: number;
        temperature: number;
    }
}
