/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const PredictAgentOutput: core.serialization.ObjectSchema<
    serializers.PredictAgentOutput.Raw,
    SuperAgent.PredictAgentOutput
> = core.serialization.object({
    success: core.serialization.boolean(),
    data: core.serialization.string(),
    trace: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace PredictAgentOutput {
    interface Raw {
        success: boolean;
        data: string;
        trace: Record<string, unknown>;
    }
}
