/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const PrismaModelsAgentDatasource: core.serialization.ObjectSchema<
    serializers.PrismaModelsAgentDatasource.Raw,
    SuperAgent.PrismaModelsAgentDatasource
> = core.serialization.object({
    agentId: core.serialization.string(),
    datasourceId: core.serialization.string(),
    agent: core.serialization.lazyObject(async () => (await import("..")).PrismaModelsAgent).optional(),
    datasource: core.serialization.lazyObject(async () => (await import("..")).PrismaModelsDatasource).optional(),
    createdAt: core.serialization.date(),
    updatedAt: core.serialization.date(),
});

export declare namespace PrismaModelsAgentDatasource {
    interface Raw {
        agentId: string;
        datasourceId: string;
        agent?: serializers.PrismaModelsAgent.Raw | null;
        datasource?: serializers.PrismaModelsDatasource.Raw | null;
        createdAt: string;
        updatedAt: string;
    }
}
