/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const PrismaModelsAgent: core.serialization.ObjectSchema<
    serializers.PrismaModelsAgent.Raw,
    SuperAgent.PrismaModelsAgent
> = core.serialization.object({
    id: core.serialization.string(),
    name: core.serialization.string(),
    avatar: core.serialization.string().optional(),
    initialMessage: core.serialization.string().optional(),
    description: core.serialization.string(),
    isActive: core.serialization.boolean(),
    createdAt: core.serialization.date(),
    updatedAt: core.serialization.date(),
    llms: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("..")).PrismaModelsAgentLlm))
        .optional(),
    llmModel: core.serialization.lazy(async () => (await import("..")).LlmModel),
    prompt: core.serialization.string().optional(),
    apiUserId: core.serialization.string(),
    apiUser: core.serialization.lazyObject(async () => (await import("..")).PrismaModelsApiUser).optional(),
    datasources: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("..")).PrismaModelsAgentDatasource))
        .optional(),
    tools: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("..")).PrismaModelsAgentTool))
        .optional(),
    workflowSteps: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("..")).PrismaModelsWorkflowStep))
        .optional(),
});

export declare namespace PrismaModelsAgent {
    interface Raw {
        id: string;
        name: string;
        avatar?: string | null;
        initialMessage?: string | null;
        description: string;
        isActive: boolean;
        createdAt: string;
        updatedAt: string;
        llms?: serializers.PrismaModelsAgentLlm.Raw[] | null;
        llmModel: serializers.LlmModel.Raw;
        prompt?: string | null;
        apiUserId: string;
        apiUser?: serializers.PrismaModelsApiUser.Raw | null;
        datasources?: serializers.PrismaModelsAgentDatasource.Raw[] | null;
        tools?: serializers.PrismaModelsAgentTool.Raw[] | null;
        workflowSteps?: serializers.PrismaModelsWorkflowStep.Raw[] | null;
    }
}
