/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const PromptListOutput: core.serialization.ObjectSchema<
    serializers.PromptListOutput.Raw,
    SuperAgent.PromptListOutput
> = core.serialization.object({
    success: core.serialization.boolean(),
    data: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("..")).AppLibModelsResponsePrompt)
    ),
});

export declare namespace PromptListOutput {
    interface Raw {
        success: boolean;
        data: serializers.AppLibModelsResponsePrompt.Raw[];
    }
}
