/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const PromptOutput: core.serialization.ObjectSchema<serializers.PromptOutput.Raw, SuperAgent.PromptOutput> =
    core.serialization.object({
        success: core.serialization.boolean(),
        data: core.serialization.lazyObject(async () => (await import("..")).AppLibModelsResponsePrompt).optional(),
    });

export declare namespace PromptOutput {
    interface Raw {
        success: boolean;
        data?: serializers.AppLibModelsResponsePrompt.Raw | null;
    }
}
