/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const SignInOutput: core.serialization.ObjectSchema<serializers.SignInOutput.Raw, SuperAgent.SignInOutput> =
    core.serialization.object({
        success: core.serialization.boolean(),
        data: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    });

export declare namespace SignInOutput {
    interface Raw {
        success: boolean;
        data: Record<string, unknown>;
    }
}
