/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const TagListOutput: core.serialization.ObjectSchema<serializers.TagListOutput.Raw, SuperAgent.TagListOutput> =
    core.serialization.object({
        success: core.serialization.boolean(),
        data: core.serialization.list(
            core.serialization.lazyObject(async () => (await import("..")).AppLibModelsResponseTag)
        ),
    });

export declare namespace TagListOutput {
    interface Raw {
        success: boolean;
        data: serializers.AppLibModelsResponseTag.Raw[];
    }
}
