/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const TagOutput: core.serialization.ObjectSchema<serializers.TagOutput.Raw, SuperAgent.TagOutput> =
    core.serialization.object({
        success: core.serialization.boolean(),
        data: core.serialization.lazyObject(async () => (await import("..")).AppLibModelsResponseTag).optional(),
    });

export declare namespace TagOutput {
    interface Raw {
        success: boolean;
        data?: serializers.AppLibModelsResponseTag.Raw | null;
    }
}
