/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const ToolAssistantToolsCode: core.serialization.ObjectSchema<
    serializers.ToolAssistantToolsCode.Raw,
    SuperAgent.ToolAssistantToolsCode
> = core.serialization.object({});

export declare namespace ToolAssistantToolsCode {
    interface Raw {}
}
