/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const ToolOutput: core.serialization.ObjectSchema<serializers.ToolOutput.Raw, SuperAgent.ToolOutput> =
    core.serialization.object({
        success: core.serialization.boolean(),
        data: core.serialization.lazyObject(async () => (await import("..")).AppLibModelsResponseTool).optional(),
    });

export declare namespace ToolOutput {
    interface Raw {
        success: boolean;
        data?: serializers.AppLibModelsResponseTool.Raw | null;
    }
}
