/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const ToolAssistantToolsRetrieval: core.serialization.ObjectSchema<
    serializers.ToolAssistantToolsRetrieval.Raw,
    SuperAgent.ToolAssistantToolsRetrieval
> = core.serialization.object({});

export declare namespace ToolAssistantToolsRetrieval {
    interface Raw {}
}
