/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const User: core.serialization.ObjectSchema<serializers.User.Raw, SuperAgent.User> = core.serialization.object({
    id: core.serialization.string(),
    email: core.serialization.string(),
    password: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    createdAt: core.serialization.date().optional(),
    updatedAt: core.serialization.date().optional(),
    deletedAt: core.serialization.date().optional(),
    provider: core.serialization.string().optional(),
    accessToken: core.serialization.string().optional(),
});

export declare namespace User {
    interface Raw {
        id: string;
        email: string;
        password?: string | null;
        name?: string | null;
        createdAt?: string | null;
        updatedAt?: string | null;
        deletedAt?: string | null;
        provider?: string | null;
        accessToken?: string | null;
    }
}
