/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const UserOutput: core.serialization.ObjectSchema<serializers.UserOutput.Raw, SuperAgent.UserOutput> =
    core.serialization.object({
        success: core.serialization.boolean(),
        data: core.serialization.lazyObject(async () => (await import("..")).User).optional(),
    });

export declare namespace UserOutput {
    interface Raw {
        success: boolean;
        data?: serializers.User.Raw | null;
    }
}
