/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const VectorDbProvider: core.serialization.Schema<
    serializers.VectorDbProvider.Raw,
    SuperAgent.VectorDbProvider
> = core.serialization.enum_(["PINECONE", "ASTRA_DB", "WEAVIATE", "QDRANT", "SUPABASE"]);

export declare namespace VectorDbProvider {
    type Raw = "PINECONE" | "ASTRA_DB" | "WEAVIATE" | "QDRANT" | "SUPABASE";
}
