/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const VectorDbList: core.serialization.ObjectSchema<serializers.VectorDbList.Raw, SuperAgent.VectorDbList> =
    core.serialization.object({
        success: core.serialization.boolean(),
        data: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("..")).PrismaModelsVectorDb))
            .optional(),
    });

export declare namespace VectorDbList {
    interface Raw {
        success: boolean;
        data?: serializers.PrismaModelsVectorDb.Raw[] | null;
    }
}
