/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const WorkflowConfig: core.serialization.ObjectSchema<
    serializers.WorkflowConfig.Raw,
    SuperAgent.WorkflowConfig
> = core.serialization.object({
    id: core.serialization.string(),
    config: core.serialization.unknown().optional(),
    createdAt: core.serialization.date(),
    updatedAt: core.serialization.date(),
    workflowId: core.serialization.string(),
    workflow: core.serialization.lazyObject(async () => (await import("..")).PrismaModelsWorkflow).optional(),
    apiUser: core.serialization.property(
        "ApiUser",
        core.serialization.lazyObject(async () => (await import("..")).PrismaModelsApiUser).optional()
    ),
    apiUserId: core.serialization.string().optional(),
});

export declare namespace WorkflowConfig {
    interface Raw {
        id: string;
        config?: unknown | null;
        createdAt: string;
        updatedAt: string;
        workflowId: string;
        workflow?: serializers.PrismaModelsWorkflow.Raw | null;
        ApiUser?: serializers.PrismaModelsApiUser.Raw | null;
        apiUserId?: string | null;
    }
}
