/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const WorkflowList: core.serialization.ObjectSchema<serializers.WorkflowList.Raw, SuperAgent.WorkflowList> =
    core.serialization.object({
        success: core.serialization.boolean(),
        data: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("..")).PrismaModelsWorkflow))
            .optional(),
    });

export declare namespace WorkflowList {
    interface Raw {
        success: boolean;
        data?: serializers.PrismaModelsWorkflow.Raw[] | null;
    }
}
