/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as SuperAgent from "../../api";
import * as core from "../../core";

export const WorkflowStepList: core.serialization.ObjectSchema<
    serializers.WorkflowStepList.Raw,
    SuperAgent.WorkflowStepList
> = core.serialization.object({
    success: core.serialization.boolean(),
    data: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("..")).PrismaModelsWorkflowStep))
        .optional(),
});

export declare namespace WorkflowStepList {
    interface Raw {
        success: boolean;
        data?: serializers.PrismaModelsWorkflowStep.Raw[] | null;
    }
}
