/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as SuperAgent from "../../../../../api";
import * as core from "../../../../../core";

export const AppLibModelsTagTag: core.serialization.Schema<
    serializers.AppLibModelsTagTag.Raw,
    SuperAgent.AppLibModelsTagTag
> = core.serialization.object({
    name: core.serialization.string(),
    color: core.serialization.string(),
});

export declare namespace AppLibModelsTagTag {
    interface Raw {
        name: string;
        color: string;
    }
}
