/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AppModelsRequestWorkflowStep {
    order: number;
    agentId: string;
    input: string;
    output: string;
}
