/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         input: "string",
 *         enableStreaming: true
 *     }
 */
export interface WorkflowInvoke {
    input: string;
    enableStreaming: boolean;
    sessionId?: string;
    outputSchemas?: Record<string, string>;
}
