/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Document {
    type: string;
    url: string;
    name: string;
    authorization?: Record<string, unknown>;
    fromPage?: number;
    toPage?: number;
    splitter?: Record<string, unknown>;
}
