/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as SuperAgent from "../../../../../api";
import * as core from "../../../../../core";

export const AgentTool: core.serialization.Schema<serializers.AgentTool.Raw, SuperAgent.AgentTool> =
    core.serialization.object({
        agentId: core.serialization.string(),
        toolId: core.serialization.string(),
    });

export declare namespace AgentTool {
    interface Raw {
        agentId: string;
        toolId: string;
    }
}
