/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as SuperAgent from "../../../../../api";
import * as core from "../../../../../core";

export const AppLibModelsAgentToolAgentTool: core.serialization.Schema<
    serializers.AppLibModelsAgentToolAgentTool.Raw,
    SuperAgent.AppLibModelsAgentToolAgentTool
> = core.serialization.object({
    agentId: core.serialization.string(),
    toolId: core.serialization.string(),
});

export declare namespace AppLibModelsAgentToolAgentTool {
    interface Raw {
        agentId: string;
        toolId: string;
    }
}
