/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SuperAgent from "../../../..";

/**
 * @example
 *     {
 *         input: "string",
 *         enableStreaming: false,
 *         llmParams: {
 *             maxTokens: 1,
 *             temperature: 1.1
 *         }
 *     }
 */
export interface AgentInvokeRequest {
    input: string;
    sessionId?: string;
    outputSchema?: string;
    llmParams?: SuperAgent.LlmParams;
}
