/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AppLibModelsAgentAgent {
    name: string;
    type: string;
    description?: string;
    avatarUrl?: string;
    llm?: Record<string, unknown>;
    hasMemory?: boolean;
    promptId?: string;
}
