/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         datasourceId: "datasourceId"
 *     }
 */
export interface AppModelsRequestAgentDatasource {
    datasourceId: string;
}
