/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SuperAgent from "../../../..";

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface AppModelsRequestAgent {
    isActive?: boolean;
    name: string;
    initialMessage?: string;
    prompt?: string;
    llmModel?: string;
    llmProvider?: SuperAgent.LlmProvider;
    description?: string;
    avatar?: string;
    type?: SuperAgent.AgentType;
    parameters?: SuperAgent.OpenAiAssistantParameters;
    metadata?: Record<string, unknown>;
    outputSchema?: string;
}
