/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         llmId: "llmId"
 *     }
 */
export interface AppModelsRequestAgentLlm {
    llmId: string;
}
