/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AppModelsRequestAgentInvoke {
    input: string;
    sessionId?: string;
    enableStreaming: boolean;
    outputSchema?: string;
}
