/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SuperAgent from "../../../..";

export interface InvokeApiV1AgentsAgentIdInvokePostStreamRequest {
    input: string;
    sessionId?: string;
    outputSchema?: string;
    llmParams?: SuperAgent.LlmParams;
}
